import { Raleway, Inter } from "next/font/google";
import "./globals.css";
import topbar from "./_components/topbar";
import Navbar from "./_components/Navbar";
import "leaflet/dist/leaflet.css";
import Navbar2 from "./_components/Navbar2";

const raleway = Raleway({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${inter.variable}  antialiased`}>
        <Navbar2 />
        {children}
      </body>
    </html>
  );
}
