import { Raleway } from "next/font/google";
import "./globals.css";
import topbar from "./_components/topbar";
import Navbar from "./_components/Navbar";

const raleway = Raleway({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
