import { Raleway, Inter } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import Navbar2 from "./_components/Navbar2";

const raleway = Raleway({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "eassy parking ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="76318674-9c38-4c3c-9847-5850054358ca"
        ></script>
      </head>
      <body className={`${raleway.variable} ${inter.variable}  antialiased`}>
        <Navbar2 />
        <main className="mt-[90px]">{children}</main>
      </body>
    </html>
  );
}
